MONGODB_HOST: mongodb.daws88s.fun
MYSQL_HOST: mysql.daws88s.fun
REDIS_HOST: redis.daws88s.fun
CATALOGUE_HOST: catalogue.daws88s.fun
USER_HOST: user.daws88s.fun
SHIPPING_HOST: shipping.daws88s.fun
RABBITMQ_HOST: rabbitmq.daws88s.fun
PAYMENT_HOST: payment.daws88s.fun
CART_HOST: cart.daws88s.fun
