[mongodb]
mongodb.daws88s.fun

[redis]
redis.daws88s.fun

[mysql]
mysql.daws88s.fun

[rabbitmq]
rabbitmq.daws88s.fun

[catalogue]
catalogue.daws88s.fun

[user]
user.daws88s.fun

[cart]
cart.daws88s.fun

[shipping]
shipping.daws88s.fun

[payment]
payment.daws88s.fun

[local]
localhost

[frontend]
daws88s.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321