- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Install the latest version of Apache and MariaDB
  ansible.builtin.dnf:
    name: "{{ item }}"
  state: latest
  loop:
  - openssl
  - openssl-libs
  - openssh
  - openssh-server
  - openssh-client

- name: pythonetup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
